analytics: {}
color:
  brandColors:
    - '#FFFFFF'
    - '#EA6E24'
    - '#F1C644'
    - '#6896B8'
    - '#15140D'
  brandStrength: 0.501125
  lightness: 0.754504
  rhythmicContrast: 0.64527
  saturation: 0.193693
cta: {}
layout_spectrum: 1
name: Jack on Marketing
opengraph: {}
purpose: []
typography_spectrum: 0.6306
