name: Jack on Marketing
favicon: null
layout_spectrum: 0.27541
typography_spectrum: 0.6306
title: Jack on Marketing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
