name: Jack on Marketing
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5495
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#EA6E24'
    - '#F1C644'
    - '#6896B8'
    - '#15140D'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.64527
purpose: []
